# Generated by Django 5.0.4 on 2024-04-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ai_analysis_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(default=None, max_length=255, null=True)),
                ('success', models.BooleanField()),
                ('message', models.CharField(default=None, max_length=255, null=True)),
                ('class_name', models.IntegerField(default=None, null=True)),
                ('confidence', models.DecimalField(decimal_places=4, default=None, max_digits=5, null=True)),
                ('request_timestamp', models.DateTimeField(default=None, null=True)),
                ('response_timestamp', models.DateTimeField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_analysis_logs',
            },
        ),
    ]
